### ISSUE TITLE
No module named 'secrets'

### ISSUE THREAD

**Issue by trueman007** [ojroques/Garbled-Circuit#1]
python3 main.py bob
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    import util # ClientSocket, log, ServerSocket
  File "/home/chlf/fromgit/Garbled-Circuit/src/util.py", line 7, in <module>
    import secrets      # randbits
ImportError: No module named 'secrets'
make: *** [bob] Error 1

**Comment by trueman007** [comment]
update to python 3.6 will solve this problem
